---
- name: (SCHEDULE) create restic systemd timer
  ansible.builtin.include_tasks: restic_create_systemd.yml
  when:
    - ansible_service_mgr == 'systemd'
    - restic_create_schedule | bool

- name: (SCHEDULE) delete systemd timers if available
  ansible.builtin.include_tasks: restic_delete_systemd.yml
  when:
    - ansible_service_mgr == 'systemd'
    - restic_create_schedule | bool
